### PR TITLE
Added show/hide password functionality

### LINKED ISSUE #8: Show/Hide password functionality

### PR DESCRIPTION
**Pull request by DineshKoushik**
# Description
This PR solves the issue of introducing show/hide password functionality.
# 
#
# Screenshot
Screenshot (128)

# 
# 

- [x] Added show/hide password checkbox.

closes #8

### CODE REVIEW

**Comment by DineshKoushik** [comment]
@somya51p , Hello can you verify this PR please.

**Comment by somya51p** [comment]
Nice work @DineshKoushik, but can you please add the Eye icon in place of the Checkbox.

**Comment by DineshKoushik** [comment]
image


@somya51p , Check this new PR.

**Comment by DineshKoushik** [comment]
@somya51p , Check this new PR.

**Comment by somya51p** [comment]
@DineshKoushik Align this icon with the password label. 

Capture

**Comment by DineshKoushik** [comment]
image

@somya51p , Does this works?

**Comment by somya51p** [comment]
@DineshKoushik Good work!

**Pull request merged**
